### ISSUE TITLE
The following leaks were detected:_Promise, clone, exceptions

### ISSUE THREAD

**Issue by sean-hill** [devinivy/labbable#1]
I've got my tests to run using `labbable` and `glue`, but they keep failing because of this error (since I started using `labbable`, any suggestions?

```
const Code = require('code')
const Lab = require('lab')
const lab = exports.lab = Lab.script()
const LabbableServer = require('../server')

lab.experiment('User', () => {
  let server
  /**
   * Initialize Server before tests
   */
  lab.before((done) => {
    LabbableServer.ready((err, svr) => {
      if (err) {
        return done(err)
      }
      server = svr
      done()
    })
  })

  /**
   *  Test 123
   */
  lab.test('Test 123', (done) => {
    Code.expect(server).to.exist()
    done()
  })
})
```

**Comment by devinivy** [comment]
Labbable doesn't have any dependencies, and it doesn't leak any of those variables into the global namespace.  You'll have to look into finding some other library in your project that leaks those global variables– perhaps something you `require()` in `../server`?  If it's not something you can fix, lab does have an `--ignore` flag where you can list global variables to ignore.

**Comment by sean-hill** [comment]
Thanks :)

**Comment by devinivy** [comment]
Cheers– good luck!
