### ISSUE TITLE
server.inject throw "Method not available when the selection has more than one connection or none"

### ISSUE THREAD

**Issue by anhntbk08** [devinivy/labbable#10]
Hello

Thank for your great work so far.

My server is successfully initialized on test mode but whenever i tried to use inject, it throws `Method not available when the selection has more than one connection or none`

Can you please point me out on this issue?

Appreciate your help.

Tuan.

**Comment by devinivy** [comment]
Hi @anhntbk08– `server.inject()` only works when your server has a single connection.  It sounds like your server uses multiple connections.  Instead you'll want to call `inject()` on the specific connection you'd like to test, e.g. `server.connections[1].inject({/* ... */)`.
