### ISSUE TITLE
Missed Line

### ISSUE THREAD

**Issue by Zedonboy** [devinivy/labbable#11]
This is not an issue,  i dont know what "missed line"  mean,  because i dont know why labbable should miss a line when there is no condition and u properly exported my server to labbable.  please help me out

**Comment by devinivy** [comment]
Could you provide a little more info?  If you could share the full error you're seeing, perhaps we can help you out.

**Comment by Zedonboy** [comment]
Hi @devinivy  i mean the html output, some part of my code was highlighted. with missed a line tooltip.

moreover am receiving script error, Timeout error. 
   ``` Timed out (2000ms) - Before My server
  at Timeout.setTimeout (C:\Users\Declan\AppData\Roaming\npm\node_modules\lab\lib\runner.js:582:23)
  at ontimeout (timers.js:469:11)
  at tryOnTimeout (timers.js:304:5)
  at Timer.listOnTimeout (timers.js:264:5) ```

i dont know what timeout error means in unit testing context errors. 
Please am a novice in Unit testing

**Comment by devinivy** [comment]
Sorry, with this information I can't help you or verify if labbable is part of your problem!  We can re-open if there's more info to work from.
