### ISSUE TITLE
Possible error in README.md

### ISSUE THREAD

**Issue by webbpinner** [devinivy/labbable#8]
I just successfully implemented Labbable on my project but only after adding this line to beginning of test/index.js in the glue example (~line 9).
`const before = lab.before;`

Not sure if this is an issue with the provided example or just my project but I though I'd share.

Thanks,
-Webb

**Comment by devinivy** [comment]
This is indeed a bug with the example– thanks!

**Comment by terryx** [comment]
i just saw this issue after i made a pull request https://github.com/devinivy/labbable/pull/9

**Comment by devinivy** [comment]
Closed by #9
